services:
  postgres-cinema-reservation:
    image: kintamani/cinema-reservation-db:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=${BLUEPRINT_DB_DATABASE}
      - POSTGRES_USER=${BLUEPRINT_DB_USERNAME}
      - POSTGRES_PASSWORD=${BLUEPRINT_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5432"
    volumes:
      - ./docker/postgres//data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${BLUEPRINT_DB_USERNAME} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_volume:
